### PR TITLE
Fix security vulnerabilities

### PR DESCRIPTION
**Pull request by ruslan-bikkinin**
This PR fixes security vulnerabilities for current version of send-transform. All tests are passed.

### CODE REVIEW

**Comment by TimBarham** [comment]
If you're going to go the route of updating my fork, I'd rather keep it in sync with the original as much as possible. 

That would mean applying my changes on top of the latest release of _send_. However, I notice you've updated some of the dependencies here to newer versions than those used by the latest release of _send_ - does that mean the versions currently used by _send_ have security vulnerabilities?

**Comment by ruslan-bikkinin** [comment]
Hi @TimBarham and thanks for responding so quick. Yes, you are right, current version of send 0.16.2 is vulnerable as well, although the version from master branch is not vulnerable. The thing is that we don't know whether it stable or not until folks from send release something from it. What I did in this PR is just bumped deps to the minimal accepted versions which are not vulnerable. Some tests were broken after moving to  supertest v3.0.0, so I fixed them using this commits:
https://github.com/pillarjs/send/commit/fe8837c4698610b26ad5e86adee3e6666d7cda45
https://github.com/pillarjs/send/commit/3d21f2ed1c5a45710c570ae7f54ea8a59f5cfd29
https://github.com/pillarjs/send/commit/31c5277ce1e76d02ee68a593ee23248800eb6ca7#diff-e8c827528cad5120d12011d3c3231821

**Comment by ruslan-bikkinin** [comment]
@TimBarham I agree with you, that using the most recent version of send is more preferred but, unfortunately, we cannot wait until guys who maintain it release new version because security vulnerabilities should be fixed ASAP. If you don't see any other concerns about this PR, please, let's get it merged.

**Comment by ruslan-bikkinin** [comment]
@TimBarham just a friendly ping on this.

**Pull request merged**
